# Generated by Django 3.0.8 on 2020-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('by', models.CharField(blank=True, default='', max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(blank=True, default='')),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('blogPageImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('blogPageContent', models.TextField(blank=True, default='')),
                ('blogPageImage2', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('blogPageContent2', models.TextField(blank=True, default='')),
                ('blogPageImage3', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('blogPageContent3', models.TextField(blank=True, default='')),
            ],
        ),
    ]
