# Generated by Django 3.0.8 on 2020-12-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='blogPageContent',
            new_name='articlePageContent',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='blogPageContent2',
            new_name='articlePageContent2',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='blogPageContent3',
            new_name='articlePageContent3',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='blogPageImage',
            new_name='articlePageImage',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='blogPageImage2',
            new_name='articlePageImage2',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='blogPageImage3',
            new_name='articlePageImage3',
        ),
    ]
