# Generated by Django 3.0.8 on 2020-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201205_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='podcastSummary',
        ),
        migrations.AddField(
            model_name='article',
            name='podcast',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
