# Generated by Django 3.0.8 on 2020-12-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201205_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profilePic',
            field=models.ImageField(blank=True, default='', upload_to='blog/images/'),
        ),
    ]
