# Generated by Django 3.0.8 on 2020-12-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='', max_length=4),
        ),
    ]
